// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: novelChapter.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class NovelChapterItemResponse;
@class NovelChapterVolumeResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NovelChapterRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NovelChapterRoot : GPBRootObject
@end

#pragma mark - NovelChapterResponse

typedef GPB_ENUM(NovelChapterResponse_FieldNumber) {
  NovelChapterResponse_FieldNumber_Errnum = 1,
  NovelChapterResponse_FieldNumber_Errmsg = 2,
  NovelChapterResponse_FieldNumber_Data_p = 3,
};

GPB_FINAL @interface NovelChapterResponse : GPBMessage

@property(nonatomic, readwrite) int32_t errnum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errmsg;

@property(nonatomic, readwrite, strong, null_resettable) NovelChapterVolumeResponse *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NovelChapterVolumeResponse

typedef GPB_ENUM(NovelChapterVolumeResponse_FieldNumber) {
  NovelChapterVolumeResponse_FieldNumber_VolumeId = 1,
  NovelChapterVolumeResponse_FieldNumber_VolumeName = 2,
  NovelChapterVolumeResponse_FieldNumber_VolumeOrder = 3,
  NovelChapterVolumeResponse_FieldNumber_ChaptersArray = 4,
};

GPB_FINAL @interface NovelChapterVolumeResponse : GPBMessage

@property(nonatomic, readwrite) int32_t volumeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *volumeName;

@property(nonatomic, readwrite) int32_t volumeOrder;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NovelChapterItemResponse*> *chaptersArray;
/** The number of items in @c chaptersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger chaptersArray_Count;

@end

#pragma mark - NovelChapterItemResponse

typedef GPB_ENUM(NovelChapterItemResponse_FieldNumber) {
  NovelChapterItemResponse_FieldNumber_ChapterId = 1,
  NovelChapterItemResponse_FieldNumber_ChapterName = 2,
  NovelChapterItemResponse_FieldNumber_ChapterOrder = 3,
};

GPB_FINAL @interface NovelChapterItemResponse : GPBMessage

@property(nonatomic, readwrite) int32_t chapterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *chapterName;

@property(nonatomic, readwrite) int32_t chapterOrder;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
